# Generated by Django 4.2.4 on 2023-09-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_player_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahtzeeScorecard',
            fields=[
                ('scorecard_id', models.AutoField(primary_key=True, serialize=False)),
                ('ones', models.IntegerField(default=0)),
                ('twos', models.IntegerField(default=0)),
                ('threes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('fives', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('upper_bonus', models.IntegerField(default=0)),
                ('three_of_a_kind', models.IntegerField(default=0)),
                ('four_of_a_kind', models.IntegerField(default=0)),
                ('full_house', models.IntegerField(default=0)),
                ('small_straight', models.IntegerField(default=0)),
                ('large_straight', models.IntegerField(default=0)),
                ('yahtzee', models.IntegerField(default=0)),
                ('yahtzee_bonus', models.IntegerField(default=0)),
                ('chance', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.player')),
            ],
        ),
    ]
