# Generated by Django 4.2.4 on 2023-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_yahtzeescorecard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yahtzeescorecard',
            old_name='total',
            new_name='grand_total',
        ),
        migrations.AddField(
            model_name='yahtzeescorecard',
            name='lower_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yahtzeescorecard',
            name='upper_total',
            field=models.IntegerField(default=0),
        ),
    ]
