# Generated by Django 4.2.4 on 2023-09-09 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_total_yahtzeescorecard_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahtzeescorecard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
